name: backend ci workflow

on: 
    push:
        branches:
            - main
        paths:
            - backend/**

jobs:
    build-backend:
        runs-on: ubuntu-latest 
            
        steps:
            -  name: Set up QEMU
               uses: docker/setup-qemu-action@v3
            
            -  name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
            
            -  name: Login to Docker Hub
               uses: docker/login-action@v3
               with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            -  name: Build and push
               uses: docker/build-push-action@v6
               with:
                push: true
                tags: fenilcodes/paytm:backend
    
    deploy-backend:
        runs-on: ubuntu-latest
        
        steps:
         - name: Deploy Backend to EC2
           uses: appleboy/ssh-action@master
           with:
            host: ${{ secrets.BACKEND_SSH_HOST }}
            username: ${{ secrets.FRONTEND_SSH_USERNAME }}
            key: ${{ secrets.FRONTEND_SSH_KEY }}
            script: |
                sudo docker pull fenilscodes/paytm:backend
                sudo docker stop paytm:backend || true
                sudo docker rm paytm:backend || true
                sudo docker run -d --name backend -p 5173:5173 fenilscodes/paytm:backend            