name: backend ci workflow

on: 
    push:
        branches:
            - main
        paths:
            - backend/**

jobs:
    build-backend:
        runs-on: ubuntu-latest 
            
        steps:

            -  name: Checkout code
               uses: actions/checkout@v3

            -  name: List files in the repository
               run: ls -R

            -  name: Set up QEMU
               uses: docker/setup-qemu-action@v3
            
            -  name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
            
            -  name: Login to Docker Hub
               uses: docker/login-action@v3
               with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            
            -  name: Build and push
               uses: docker/build-push-action@v6
               with:
                context: ./backend
                push: true
                tags: fenilcodes/paytm:backend
    
    deploy-backend:
        needs: build-backend
        runs-on: ubuntu-latest
        
        steps:
         - name: Deploy Backend to EC2
           uses: appleboy/ssh-action@master
           with:
            host: ${{ secrets.BACKEND_SSH_HOST }}
            username: ${{ secrets.FRONTEND_SSH_USERNAME }}
            key: ${{ secrets.FRONTEND_SSH_KEY }}
            script: |
                sudo docker stop backend || true
                sudo docker rm backend || true
                sudo docker rmi fenilcodes/paytm:backend || true
                sudo docker pull fenilcodes/paytm:backend
                sudo docker run -d --name backend -p 3000:3000 -e DATABASE_URL=${{ secrets.DATABASE_URL }} fenilcodes/paytm:backend